### ISSUE TITLE
timezone name not found

### ISSUE THREAD

**Issue by efreeman518** [RobThree/TimeZoneMapper#2]
Calcutta name changed officially to Kolkata.
Timezone service lookup based on lat/lon returns "Asia/Kolkata"

TimeZoneMap.OnlineWithFallbackValuesTZMapper.MapTZID("Asia/Kolkata") fails - The given key was not present in the dictionary.

TimeZoneMap.OnlineWithFallbackValuesTZMapper.MapTZID("Asia/Calcutta") works - but it is the old city name that is not current.

**Comment by RobThree** [comment]
Asia/Kolkata is not (yet?) published by the Unicode Consortium in their latest [CLDR data](http://unicode.org/repos/cldr/trunk/common/supplemental/windowsZones.xml) which is why the the timezone is not (yet) found. You can save an offline version of the file. modify it and use that with a CustomValuesTZMapper instead.
